name: CI
on: push
jobs:
  build:
    name: Build & test
    strategy:
      matrix:
        include:
          - platform: windows
            os: "windows-2019"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-distributables
          path: dist/HttpToolkit-*
          if-no-files-found: error
  publish:
    name: Publish a release
    runs-on: "ubuntu-20.04"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
      - name: Get all distributables
        uses: actions/download-artifact@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: true

      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: ./*/
